import "./styles/app.css";
// import { ErrorWrapper } from "./error-wrapper";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: 'My App',
    template: '%s | My App',
  },
  description: 'My App Description',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h3>Root Layout Header</h3>
        </header>
        <div style={{ padding: '0.5rem' }}>
          {/* <ErrorWrapper> */}
            {children}
          {/* </ErrorWrapper> */}
        </div>
        <footer>
          <h3>Root Layout Footer</h3>
        </footer>
      </body>
    </html>
  );
}
